---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kasten
spec:
  dependsOn:
    - name: prometheus
      namespace: observability
  values:
    global:
      persistence:
        storageClass: ceph-block
      prometheus:
        external:
          host: ""
          port: ""
          baseURL: ""
    eula:
      accept: true
    prometheus:
      networkPolicy:
        enabled: false
      server:
        enabled: false
    metering:
      mode: airgap
    auth:
      groupAllowList: []
      oidcAuth:
        enabled: true
        secretName: k10-oidc-auth
      k10AdminUsers: []
      k10AdminGroups: []
    grafana:
      enabled: false
    encryption:
      primaryKey:
        vaultTransitKeyName: kasten
        vaultTransitPath: /transit
    vault:
      secretName: k10-vault-auth
