---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kasten
spec:
  values:
    genericVolumeSnapshot:
      resources: {}
    global:
      imageRenderer:
        resources: {}
      initChownData:
        resources: {}
      resources: {}
      sidecar:
        resources: {}
    resources: {}
    auth:
      tokenAuth:
        enabled: true
      oidcAuth:
        enabled: false
    eula:
      company: ABC
      email: admin@example.com
    executorReplicas: 1
    gateway:
      insecureDisableSSLVerify: true
      resources: {}
    grafana:
      enabled: false
