{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bored-agent.serviceAccountName" . }}-impersonate
  labels:
    app.kubernetes.io/created-by: resource-stack
    app.kubernetes.io/managed-by: Lens
    app.kubernetes.io/name: lens-spaces-agent
    {{- include "bored-agent.labels" . | nindent 4 }}
rules:
  - verbs:
      - impersonate
    apiGroups:
      - ''
    resources:
      - users
      - groups
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bored-agent.serviceAccountName" . }}-updater
  labels:
    app.kubernetes.io/created-by: resource-stack
    app.kubernetes.io/managed-by: Lens
    app.kubernetes.io/name: lens-spaces-agent
    {{- include "bored-agent.labels" . | nindent 4 }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - namespaces
      - serviceaccounts
      - roles
      - clusterroles
      - rolebindings
      - clusterrolebindings
      - priorityclasses
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bored-agent.serviceAccountName" . }}-secret
  labels:
    app.kubernetes.io/created-by: resource-stack
    app.kubernetes.io/managed-by: Lens
    app.kubernetes.io/name: lens-spaces-agent
    {{- include "bored-agent.labels" . | nindent 4 }}
rules:
  - verbs:
      - get
      - update
      - patch
    apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - {{ include "bored-agent.serviceAccountName" . }}-cert
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bored-agent.serviceAccountName" . }}-updater
  labels:
    app.kubernetes.io/created-by: resource-stack
    app.kubernetes.io/managed-by: Lens
    app.kubernetes.io/name: lens-spaces-agent
    {{- include "bored-agent.labels" . | nindent 4 }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - deployments
      - cronjobs
      - configmaps
      - secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bored-agent.serviceAccountName" . }}-impersonate
  labels:
    app.kubernetes.io/created-by: resource-stack
    app.kubernetes.io/managed-by: Lens
    app.kubernetes.io/name: lens-spaces-agent
    {{- include "bored-agent.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bored-agent.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bored-agent.serviceAccountName" . }}-impersonate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bored-agent.serviceAccountName" . }}-updater
  labels:
    app.kubernetes.io/created-by: resource-stack
    app.kubernetes.io/managed-by: Lens
    app.kubernetes.io/name: lens-spaces-agent
    {{- include "bored-agent.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bored-agent.serviceAccountName" . }}-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bored-agent.serviceAccountName" . }}-updater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bored-agent.serviceAccountName" . }}
  labels:
    app.kubernetes.io/created-by: resource-stack
    app.kubernetes.io/managed-by: Lens
    app.kubernetes.io/name: lens-spaces-agent
    {{- include "bored-agent.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bored-agent.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bored-agent.serviceAccountName" . }}-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bored-agent.serviceAccountName" . }}-updater
  labels:
    app.kubernetes.io/created-by: resource-stack
    app.kubernetes.io/managed-by: Lens
    app.kubernetes.io/name: lens-spaces-agent
    {{- include "bored-agent.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bored-agent.serviceAccountName" . }}-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bored-agent.serviceAccountName" . }}-updater
{{- end }}
