{{- if .Values.cert.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.cert.name }}"
  labels:
    app.kubernetes.io/created-by: resource-stack
    app.kubernetes.io/managed-by: Lens
    app.kubernetes.io/name: lens-spaces-agent
    {{- include "bored-agent.labels" . | nindent 4 }}
type: Opaque
data:
  private: "{{ .Values.cert.privateKey | b64encode }}"
  public: "{{ .Values.cert.publicKey | b64encode }}"
{{- end }}
