---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: k0smotron-cluster
spec:
  # controlPlaneEndpoint:
  #   host: 1.2.3.4
  #   port: 6443
  topology: # define a managed topology
    class: k0smotron # use the ClusterClass mentioned earlier
    version: v1.21.2
    controlPlane:
      replicas: 3
    workers:
      machineDeployments:
      - class: default-worker
        name: big-pool-of-machines
        replicas: 5
    variables:
      # bundleLookupBaseRegistry: https://projects.registry.vmware.com/cluster_api_provider_bringyourownhost
      # k0sVersion: v1.27.2-k0s.0
      controlPlaneEndpointAddr: 1.2.3.4
      sans: []
      tunneling:
        enabled: false
        mode: tunnel
      args:
        - --enable-worker
        - --no-taints
