# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  dependsOn:
    - name: memcached
    - name: prometheus
  values:
    global:
      storageClass: ceph-block
    loki:
      overrideConfiguration: {}
    compactor:
      resources:
        limits: {}
        requests: {}
    gateway:
      auth:
        enabled: false
        existingSecret: ""
      resources:
        limits: {}
        requests: {}
    indexGateway:
      enabled: false
      resources:
        limits: {}
        requests: {}
    distributor:
      resources:
        limits: {}
        requests: {}
    ingester:
      resources:
        limits: {}
        requests: {}
    querier:
      resources:
        limits: {}
        requests: {}
    queryFrontend:
      resources:
        limits: {}
        requests: {}
    queryScheduler:
      resources:
        limits: {}
        requests: {}
    ruler:
      enabled: false
      resources:
        limits: {}
        requests: {}
    tableManager:
      enabled: false
      resources:
        limits: {}
        requests: {}
    promtail:
      resources:
        limits: {}
        requests: {}
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: observability
    memcachedchunks:
      enabled: false
    externalMemcachedFrontend:
      host: memcached
      port: 11211
    memcachedfrontend:
      enabled: false
    externalMemcachedIndexQueries:
      host: memcached
      port: 11211
    memcachedindexqueries:
      enabled: false
    externalMemcachedIndexWrites:
      host: memcached
      port: 11211
    memcachedindexwrites:
      enabled: false
