# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
apiVersion: v1
kind: Secret
metadata:
  name: cilium-ca-key-pair
  namespace: kube-system
type: Opaque
data:
  tls.crt: ENC[AES256_GCM,data:Jplw8QKfyy61eGsScamLX9pY0yOnXQAwmp1phgQOb8MlKoi1NlcLEgPT+D5R5KfRZCOk6K8cyP42dtSzNAwjSBjTEkO6BSO7YpSCYrACkLZXLOH0pTrc1+KN10IHXs0mfbIw84sEAmV8a4OMGlwBubZkVQEvGf0/beBcraaZGNz6caRKvuBy1JvxQD8eGTUnwDxZgwihR2gANOLqpNHq2QUQuswm1NKEJYlktqoiQM4Su7vdL8jZYtfW+UhOdT9Sgu8JG2M1q7lX2J6D9+pSJCG2c/1Hq9H9aFbOS3x/zCEw55+XS0cxCb4BCjds93WNzQT0gcrdMt5S1RGoRHkf/FK7h3ZnPUm9/P7SJWUHM/CjHxPabSJRzCk7F4myEAmSALaugqO4d7Sk0GSS+fWKPFY9FMAPnH3TxnD1z01ZX5HTfAfT//03V54E3Imn6R4XyVMOnkX3MMwGMIzMtPVe6dv5zcZZxiofpkE5T11kip7YZKUxSjvjeslHaPJYqOUBSM3HqadrtxeBTZHXpNoQSWvyaOOqutr0tpes1cHTjezSYxkzzjzVTex5QhpMcoSy5bWbk7xgB639+bOEq0L7E5xQ4Ht4Grb+BvdKNXWFlfakPVNA2SnGSvm50uRxAoeKoVH1SDYOe9YQ6AhE/6uJ0FySLHPx8sjGsVWHzqIb0Fp129VuCq0yAluwYzIYp5EC309RgI944CmRUN493kW4jmgraUres8/yzakCh8SHN5Q61QOk+riK6+aMWjrKMaJnVCK75Q5lirM/KWQM9M/3/rVipnYnrlMlugFGxqpemtC29lJ6liklvQgjeJ/sKTZdE//z4Ed4PZ59vVHWR4RL087PLOfiIif5dsUPIkDiJzUuEjlTKcAexLxvTHHhiCQ7N4CsoEEjj5s7wHTPujfmdrSkQAwob59njIItSXXv59NOOHkUwSYuRynZXcPEdEyf8ZUZHRb5py8iyNuwTvU+xaUPtTnOr7IsbZ7/YjzkGHw3ClHO1nSbSudk7IryUDxFIgMVPLhs//kgtYKQh7DqqLobO2He6cIouBLahcrmGdoKd+1iy9eonjzYTImM41lbQTjFi1yoRL6qETEg4rB5Z8IILoR9RRkgCAQ+UuGv77Ag0p2NsVgtbGhg/bcD7x1YUDErgiL186aWIkFsCS0jFk78vmLYSQYZ1kTyLID3As4YetMxEnf1vQAUDy3jT4Q1VD+H8vRHRaPH+omgbWcrEj7LIoCs6//Rml6qWEDr+ovpgYDd4Tg3j2NXrtynMkP7IS7nE+GCtXGl33O29wkYzivF9wjkbeZq5Hul6CGDodUnptXenc4PiF3PPwfH8eZobyYqXTvm8/io0LVE2KAEGBaNzzrEnx88/h4Mreb0v50iozxras7AAJGuvMtpdGqj+RXvykdHUC88BDXrqzUNjsuQ+YRfsrpYHTEjhdcnQdA/a28rxDiuXM9iWSCUJTccl7aORkdG+RmI0CfsLgkCbTfz+k3Zc+6izX083T3uCjdE/aImtemvxLzvLslVb3SMLmoJE26N8GeeK4e+DCaUWMX6UaT/RZWPWjsBbZjLQmf7elzawSe6SbWMeieFhHtlTkas1lPZhBOCFeurHcGU8M+njdoU2RlsgBa2zc72N0ptj8L2a/sGJNvTQJPk5ZZ4rLjICjkw6inGBzzec7JpqGy6SEOPtVBUpgu7wqOL97yhUnkT4YkYG/0Xo3FyxdQjRftBw3fCtBz2+esBPVKy0IYQIUDAuKY4lsm9NjE6pEPiUSaT0qA+jzaaWvwSJXaX8m0I/IWVGm2mom8SyQRsSmQ9Pl/WsN8CxAarwh3woifYM0K1xRHcYe1pIjzuFzE8gw8rSOON1JADhJs3c65pDLxG2HpSyE86nGiF470r9+RjzHPA0ktMVsJW9jwt44BKtjXppJhQqSswwis4+1TPgE2f3rUUWLaOaxcYlSLmIrFwFb0RgXSud5tyb5JQrDeMPKLTp82RngzElDhE/YO02Jvq8IYmbXH7q9oV6Q0YOXccehK7QNq89vLRtGoUUqIJr0B2/jVOuRr6vcuPBAixk0VZ3k/OUTUAw/AgQr008rQ=,iv:dBtkkj9k1lzoMBZyMN72KXMGVK/9J6m1piKTXbbK7nA=,tag:ckNfusFPePlPs2Bajrx2hg==,type:str]
  tls.key: ENC[AES256_GCM,data:fK/fjstCDHjZdPwqnAlGwkFeLxf07n9i1oZl/cjGdfUD2MPoIjfg27Jnp37fIXm/L1j74vcJnqFt9HCo3DLjmH/8cZD/r1La5a40Wbj8ZkX+TnKgTXtUsVUMvikz7k55m2bRhycYUxuh5hyFWsr+NcqQZ42DS6uIMa9QxrGihl8hnSMCBAVpFsGUZMCpo5P5+ZU5bVW9REkoQHVMjxpXOxU4ftmm7aDoQHtQ11CiYuaQpwxIFk1RrjDCuyQUauAtoZWje5QVfvHxsWF1Fnzq3sBYSSl4LWGsqnCB8rUsnAW4MfhfREx35fzx2+Fab0W+2SR6GPi7/Hwk0fpdEwyVAg/Fh86uPk97TKOHgZw5l1JGYKEXgsn+0sfW+uWkW7NTWek4xYmXx4U3HoTQNUQgTm/ljKyWFR9rIKMwMvnQVYoOwgZmccI+jprr57rUiInLnJsKwIxyDBfAIMIZ,iv:jrcaJAJv1qmJhH3Rm9ZKy143tLKi6lBgJdT4RAx8xwE=,tag:vO7aJAF1e9uIrFP29P1t5A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-07-08T17:17:25Z"
  mac: ENC[AES256_GCM,data:lZBHrTMCo7/hFCBXqLMKr/AEHl5ad6TSUncQvsNOsS5RaDaL2NLxloOpSfnxDQEGAsgkpbtVH/WuxJ5rR65b5SIKOIxgfEOfc569exyo0FSXGtcb7hA5o2zAAHpkjbL05medFWtBxlwaJGzC34GrFsqpdYNMLspWCvJz2DWfWPU=,iv:FocKcILn42K39nzFSXHGQIDyng7lBd2rMYmNP+WD5cc=,tag:ZkqQ66VMTJBgI2HYbFmE2g==,type:str]
  pgp:
    - created_at: "2023-07-08T17:17:25Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMAwXO/OIgjsG2ARAAil971PID79hsFzbArYdAHmyJu4XBgvU7MjQzlOAsUIkM
        zoaXXzsj7zdcC1L0DasIGdXyD8ftGtu3SK4SJ17sJ+kCprHLtaP7oLmJ7IXDLlkF
        r84fQMEImnFwp3j8CJqOd7vyaAWO6UJafCMcCewJwqjhRZ4CuR1gG1axx8LFYJE+
        8mCFhIaV2Yf2UzHtwi2kNKPgZ/QHkC1e4rCbF19+RQMvBEjwaZanzRGX/WT8Dkqa
        WWfj0J4j78/yTgx/XoLo3FdOx6UeLaZmKCKKKxCRbyutgWg73xE7nhBlqhPEjf1E
        hFKT+D3n4+pDqJZWFggRHzxMdjR0N6CsZwCmwzWEZZo5kxstx3hk6J3/M9JKjsLZ
        cRt2+Km/AA1MRho0yQKRRSG5Gy1Wxa+FHflfxAklME8VKpUX9CcTKhUUz85zxXF8
        95fCnVqS/pLpJdL8hdMAWWCWIlYvwXCc2h2RO5gcCVmxre/bp6f5qxhPCCQm2sBz
        1gbvCrJobvmeKg/qdt26fSZhjmzPvIUDSI1oTfR5UrdoKngoHuA5LdvLvjaVKaqv
        s0oPfr+jbeDgL/iylanvhVM+Dip9lsoi7z/eXbitiokzCYY5bB5nrXWdlz6duZ7U
        QaGjeMOWgABPS0UkQYJuJOBqsAbe54KEEIqpaN2sHNHOT0rUQrgHKtlWncu1SWzU
        aAEJAhDHbmzPi6buci3xKB92UwbVvMtJ9LD2SWMLd/jhY47+18+Ot7wDYvcoyoOu
        Iubv6OnVXqYLXtQT4u+zrnuYD0l6uQK0fhkk9m28bnIEs3ZfgqfcELrO55D5LUFn
        251RIU0kr1ZR
        =SBHu
        -----END PGP MESSAGE-----
      fp: 11AE5ED9ED4248C1318397B9AB442CFDB8ED91E4
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
