# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: flux-system
type: Opaque
data:
  username: ENC[AES256_GCM,data:KA4ThgxGlympLKUA,iv:uw7SXtKLP8va+vEZw4bQhdW2EK6s/WWEpQwQX/ZIgto=,tag:E3Ele2GNw/5eexEFDVecsA==,type:str]
  password: ENC[AES256_GCM,data:277t90OV0Y6hMzUM09Xbo+Ww+1zXBXSVv+gHybYuRFEBAyXqA0LhC747LWDvfZvP,iv:PdxKNbKdgBLZsAQUzJsHaUTx3UJ3W4uatWjYgHztF9U=,tag:c9wFHSevf4l32J/gZ3qmHg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-07-08T17:17:25Z"
  mac: ENC[AES256_GCM,data:hgmMfFO9Ugr8uwXr9RGslVjsMpznADkSZJprT8vBiv7JXQgYRgVmjWTH1XjQcmfGvBd67r3TIenciENQWo7ihh71p/SAchUoOtogtIMWIuopuU5VNbXqXixoWh9L2XK00ncPttplccHIHDQC9Y0ZlIZH2j0PjZVCtJmBToxjBlg=,iv:4yJI+V6Uix2vZknJ+Kf0vtIH+Pq6wOab/S96Gm7waK8=,tag:f76Gq/ASrL2mrKwh/h5nmQ==,type:str]
  pgp:
    - created_at: "2023-07-08T17:17:24Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMAwXO/OIgjsG2AQ/9Ff3o9BS/bg4n7i0cLg9z+AUxevmy+VMh/fegUS7tk6WZ
        R1Z1Yne1t7yyFCZzXB4WO2R5ChAIUlPysrZqNzpFAl4E9eJZFR3q+kGRQaEWsSDM
        EAZ0fnW/APFuLD15eRc/dEMJHDeq3KntoqzdJIGkiWptS60pWAKj7KDLYD5SrtgG
        YP6Ofq6BUvtl/W04hbchQeEJQGhb/dqd3FWvn+ox+wsmt3+s149+Zvnoe0TDlHlX
        FgRaqNpN+1X566kf7GLKQcvNiCjA4qMPs2HhCRoKmDEEocfxpA6W+0h542ZB6um/
        rQVPgkhswMnfSJlsDE/LC/4iSBtxoIM6ZIgu4oz1ia9KK4yFCtxDX/UtaeyuFJ/x
        MnBD7mMd02m42rHEOqTWZAf/tdLDIC9bHU+vAfjw+te1y3Nn6HR4zKxRuTAkTveZ
        wcQ1xThLB49dnV0IUbHUlBwbMwfhnJXYKnItJUSLJlVTx71ux7JwIrsjdxwcBZzS
        e0vmAkbhpba6k0fHIUfSWjLOp0JxJ3hVHyUDZYKf8pv3cBZ4fF1rN5BNuhtpme0b
        Mpbfhvceowfp1GNa556YjuVLmn1dODs5/2m52FZWPsv4D9bruyIFMOVo2XVjV4CX
        T6Cxjw+sY5jE/afx59XLoHJAWf6ad7htdFvmgd3F9Z81IeUTn9n5fF2vNbzYbe7U
        aAEJAhAqCFEQEqcQU5zOxpDfm1MFPoQs9wz8YdLrKZQ/vIhdJRfRKWRDZO5xI5Br
        z1o771jzREFV7ZeSol+Xr6WKplOz/XXZxKRipyfArhMUE7Pbq2oBr4KsY6Dsq9q7
        UV9Dg0fzy+ui
        =WUQ6
        -----END PGP MESSAGE-----
      fp: 11AE5ED9ED4248C1318397B9AB442CFDB8ED91E4
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
