# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
apiVersion: v1
kind: Secret
metadata:
  name: knative-ca-key-pair
  namespace: cert-manager
type: Opaque
data:
  tls.crt: ENC[AES256_GCM,data:RL/atkTO7qXop1Gk26fdeVZNG746l1vELDjLUrpwj6/4hNx7wR4vJmfgJ8qNEDpSelVPzZdYP8wqn63L7PDJWE0Iw9238Eg+X6na8XF9HHUVQFjiaV/8T5dJYg9IfvhT7pRFw4Vy/Gl72GWy3e37XsoKmLC0Hd3TmWEXxqgriEqg/pU7bugjUaT93X/n0oETAZAhXhaXVWur5GJ7gbbsqhnFVtL4V6JNzCKXvwpmDrHGDhsg5osZLOGBOt+bukFEtDhIkNvkQFi124LIB1RmF2gNcZvT57ktqknAKdrUjboB93HnVMH3LBI1Ey5t921XP0G/VHk8sBNZMjYft/9iPK1YyBnxaD97U/0Q9teFW0JmLLOJEAqXKLz+10M5lDbuXKYkjnmDiSPXCa0uepXK8hR1l82bmEiuC12+fBMfSc6VEtlv62Zl43UK8T9jUjBWQJhUaGP0drPycbXEA42cFP4oB5MNA2cAu6S+H44be3vKSd66uskfhF/LBNlZDrA/ZThD3afqoBuDRIOpCCVoGwq4GAJWgnDoIchz8sPTG6Fa62GADIpoVB80ogOPn7ZjXt3H2qoMLt0Y9HgXig7S71okksFFGWdUjAU/01mx9bXzl4ipesznxgG9khZLMP17xkZQGlBBTRfri6/rhAieWBuN1Pwc8CSFh9vnfu+u7XrJ4TE9TprV/qwdndTJj/7q2pG5rUkr+KFAACW0cw+bMxVNpN3F5xf03QHZWeYQxfg7DdEEEhhHnLNf44EqBjV71B+2214d4gu+5GDb8v061+pVZKErAMuBbBNbzFI9wiw9Zcirqequcu0nD+qwK9aa9v0gMJKvDZIUvKEYzYCwoKdlLN0O1icmO0ZkdeBaTUijRRUHKD3q6crS2i03IvqqOyUQRg5tfFf//58Ruaj8Rtw5bg2knwulT12r9mhmXvsFmXIN0hF4jzGQQXyckzydiRxWhfuhElMi9fPrviJkaqgV3iDhdN0rYW5mvKjmW7TDYXuvpjV/pJcH0BIlrIMNtNzf/LxGjkUEZoUibvp3+aBklVz9xPfjWx7J3itTugZ9cIak/GpFF5WNU29wT4RZ8KbaOaEsF6KYExdbtii/LC/EW0pnncMvDkxq8s/kc9BIuNO1AgXSbZLGlL/6kMFu09kINcDYRk0okgbCfHdyc/7EuOb7cITpdI2dq/10dOnfivuscPg23gttCzVMNhYftcurZuJoFHJ2VUVENecC4FFhAIl/9zBGaqWdpBozd6lpMDZFu5ccs+dtGEr6/KQySBBBkwRPIVDxS69mwcty1Q/nx8VcH/1yKM2NwTO/l68yfXjypGiqdWZe6BZkY1RxlPzfpw8T75kMqSLNgV+cIioBIQBtDMJM5TJT1CXWaG/wYfVq6LqFCmuV0shKiu1j5A0vitV83U6XF8bxjTKj15oFzMS1G1VG1HtkBHOSxrpZ2/kfX/qJxt+oMqoe7rNimoyAGswNboiwwrbqpraPcGYL1WYpb6DHYvdKXoZGchYrcpxkEQEvQKjVht6KqshafMt8SMhQqIjBTq2UctNeWjqGcW3Sh9jW23X9OsH05czIUy2cPef+bLmPuLSViOLyjC4ZigsiPCL1eskNxt4yGH0C+v+gIeWIYMNSsKkk83QOMfo+BfaASObGUdhlF5Ne64lXlYAqFnSUY7w4kj3tEgee+wkO86ozFlLfxgL8aAoAK9TTZ9Toaat7+3aWrHObny4M2qrqLVy0Hq7D36EsqbPtYX028Zx+SnePwkPf/2ZtgribcQMikMmq2i+W6NqberUeOcESFbDslHpi8LgUOCrP9eiAWACAtAXopXcP53D4Nr6AIunVS399HwM5UWqw2ySTRJLn8R3mlTWiCr4lnR1WBsMnKnNUncJLKgBdXMbkilj6PluwO0R4gUQgHGYY9YpKxw4PURJaKW4lJ29c3SOyfCGsNvl8+IfQvK6yHnsI5oaAJzSJaEMtYHBF3HNOitMkHKNu3rMPoImTrK1kYaV2A8n/WU4fX5goBtp/KDYIOnFvGWieluB8ejQBSPLYeROOLKdraPYQjpGxmJP3lVakWMGkIxbZn5lL/A0IMGacXScB,iv:Ghz0jfqZUc8J1VNKEFqF2UIlWsDqEuguNuX49rNyrFI=,tag:VmywY4k2ZSFTxlIxXR5NHg==,type:str]
  tls.key: ENC[AES256_GCM,data:O/xrrBqPT4udgLfboYkKjJqzWtLga1bv2KlA0KfU+mUBKPHTgU9G8OqZ6CtHewb01TLYEJglUG+DSA9HIJ9GSptl+IY5UcxyCxU2wNA2qgO8EK6xOf42c7wzJTaHJ+gUKSNERMpFdeZ61R6pW/Fi+MW5ombwljvwAr23InrAw1V152p8qlEmMfIUuuXMrfPhTaQhZc68dIq8sUj5/HtyXAVLoxCKAWrYH9vHYkAwImVhbaZcZYyBb2/5EGlnGmw8bfZAjasBxJlBPGy2PEfd194++fTI+TID9Ydq1XS84MiQGd7lKtn6vm2IAmWYUP+mBn1j8sig+hFqUAZuep+SK703b1NNW5wvBvK9XdVF7i2mudNSlReYj6Ydlv7neFPYYFeF8NyCzPLha4ODcP9X4x7InX2E7Wrxgw8AX6Gwuax6Ef3kGDBTLF4NcCy2x2YfTHetLPve61U=,iv:IwCEhfmJry49rE9cAjty55TyDZGdUP/iCGBz07lFsn8=,tag:p5l1ctHEEZc7fMga8xVqPQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-07-08T22:24:27Z"
  mac: ENC[AES256_GCM,data:xhNtGERboeITg8dhGIJasDhAGaNKdJR7pR46uGgge2vhlnHrtScJ+/SJY9lUrlzLSoPi2J3afsCQn1Trtx4o529HcqUUbmJ9ySvhR89w3wUCsfDUMquMPRBhELaU2czz7TG+x7HqGdbDtyqdEbyF3+li6kbzr6PjPmLU4dAxxjE=,iv:L2yBUJbrd+Xh54W5HKu2DJtDVV87syh2302VV3spznk=,tag:4UykcH2qq1ODxiyjESthuw==,type:str]
  pgp:
    - created_at: "2023-07-08T22:24:26Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMAwXO/OIgjsG2ARAAozzCsdrWYch6ZIHF4HH7zgLlhbyjRTa5oj5Eb/auRmGC
        9t33+mm1VJ8Tk2XfGPOSAPvC0+PiHV6juuGfuJOIIi2Dpo+v1UB8cPbZTPU5kIV5
        zWa5WScOqI+YWcLa552gjhHGj7vyLP+2EnnYN8mjo7wIh0eUtLagITBSxQ+uv6B9
        FJOKgbJ37ubLM0BJE7d7eByFKa2kMBxfhNfTHPtcYqMmTDEfRhG7FGvD7+c1xsvC
        R8IxRphKPnp3A74D7fZ1iFNsZ4JF40br5zAI+vMa30xsCTyyI/SYf8kPz9wH8eBD
        kEX2vV0nd/tZXKv5ffP6soto8pNhOV48aTy1RsI/JFws4mbILUatp9aKn8yXeAOG
        lmia6Lztb8uslFOsdSeA/sBT/1JpELx+AsAObaCGPBQLVHy1Gny12SHGbsqHREWD
        z8TZVaHSQJStPtTBHuiMkLqo1eBHxfICmN7mqDNaJU5ybdDlGUxc6rkRHmm5gXlT
        ypstjltJdRpu431yMK9snNUkR3eEeL7GPUxXo0hPP3rdOt7EToC1JQAVXnugl5w8
        eCuQJD/IkQ2QMF7SV1h5ZS+16saBr7JJmH89HsmvmgvexyY0z6cxIXFsG+vhokow
        kYc4k5LA0JZvpba+Ry4s2JyXYLG6l+MbOiEGDnjhMrPA1LRntS07YPJU70194tDU
        aAEJAhDw+fA8fyYb5O0Es4/rhyyoXfTyqLE7cJtvN1uj2PlJ+FD/UzLJVXY6nGii
        OKKPECTAlOjxNcEr4wbfMq8SDgK63qOugLlt/6hdZsEwlsVZBqEbySXs4aidF1cs
        nsMbTZFDKt5y
        =6P3u
        -----END PGP MESSAGE-----
      fp: 11AE5ED9ED4248C1318397B9AB442CFDB8ED91E4
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
