---
apiVersion: cloudos.anselm.es/v1alpha1
kind: ConfigDefinition
metadata:
  name: deployment
  namespace: tenant
spec:
  deployment:
    type: standalone
    standalone: {}
    clustered: {}
status: {}
