---
apiVersion: cloudos.anselm.es/v1alpha1
kind: ConfigDefinition
metadata:
  name: net
  namespace: tenant
spec:
  network:
    type: l2
    l2:
      vlan: 101
      vni: 100101
      vrf: fabric
      interfaces: []
    evpn:
      bgp:
        as: 65000
        peer:
          interfaces: []
      vrf:
        - name: blue
        - name: fabric
        - name: red
      l3:
        vlan: 3000
        vni: 103000
        vrf: fabric
status: {}
