---
apiVersion: cloudos.anselm.es/v1alpha1
kind: ConfigDefinition
metadata:
  name: ssh
  namespace: tenant
spec:
  pubkey:
    path: build/id_rsa.pub
  privkey:
    path: build/id_rsa
  providerRef:
    name: onepassword
    vault: Developer
status: {}
