# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph-csi-cephfs
spec:
  chart:
    spec:
      chart: ceph-csi-cephfs
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ceph
      version: 3.9.0
  install:
    crds: Create
    createNamespace: true
    replace: true
  interval: 1m0s
  upgrade:
    crds: CreateReplace
  postRenderers:
    - kustomize:
        images:
          - name: quay.io/cephcsi/cephcsi
          - name: registry.k8s.io/sig-storage/csi-node-driver-registrar
          - name: registry.k8s.io/sig-storage/csi-provisioner
          - name: registry.k8s.io/sig-storage/csi-resizer
          - name: registry.k8s.io/sig-storage/csi-snapshotter
