# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: maas
spec:
  dependsOn:
    - name: default-ca-issuer
    - name: prostgresql
  values:
    network:
      region_api:
        ingress:
          classes:
            namespace: cilium
            cluster: cilium
    storage:
      syslog:
        pvc:
          class_name: ceph-block
      rackd:
        pvc:
          class_name: ceph-block
    conf:
      ssh:
        private_key: null
      cloudconfig:
        override: true
        sections:
          bootcmd:
            - rm -fr /var/lib/apt/lists
            - sysctl net.ipv6.conf.all.disable_ipv6=1
            - sysctl net.ipv6.conf.default.disable_ipv6=1
            - sysctl net.ipv6.conf.lo.disable_ipv6=0
      cache:
        enabled: true
      maas:
        url:
          maas_url: http://maas-region.ucp/MAAS
        ntp:
          disable_ntpd_region: true
          disable_ntpd_rack: true
          use_external_only: true
          ntp_servers:
            - 0.ca.pool.ntp.org
            - 2.ca.pool.ntp.org
            - 3.ca.pool.ntp.org
            - 4.ca.pool.ntp.org
        dns:
          require_dnssec: "no"
          dns_servers:
            - 192.168.11.1
            - 1.1.1.1
            - 9.9.9.9
        images:
          default_os: ubuntu
          default_image: focal
          default_kernel: ga-20.04
        credentials:
          secret:
            namespace: ucp
        syslog:
          log_level: DEBUG
        extra_settings:
          active_discovery_interval: 0
          enlist_commissioning: false
          network_discovery: disabled
        system_user: null
        system_passwd: null
        tls:
          enabled: false
          create: false
    pod:
      replicas:
        rack: 2
        region: 2
        syslog: 1
      resources:
        enabled: true
    endpoints:
      maas_ingress:
        hosts:
          error_pages: null
          monitor: null
      maas_syslog:
        host_fqdn_override:
          public: maas.ucp.svc.cluster.local
      maas_region:
        name: maas-region
        scheme:
          default: http
        host_fqdn_override:
          public: maas.ucp.svc.cluster.local
    cert_manager:
      enabled: false
      create: false
      issuer:
        kind: Issuer
        name: maas-ca-issuer
    dependencies:
      static:
        bootstrap_admin_user:
          jobs:
            - maas-db-sync
          services:
            - endpoint: internal
              service: maas_region
            - endpoint: internal
              service: maas_db
        db_init:
          services:
            - endpoint: internal
              service: maas_db
        db_sync:
          jobs:
            - maas-db-init
        export_api_key:
          jobs:
            - maas-bootstrap-admin-user
          services:
            - endpoint: internal
              service: maas_region
            - endpoint: internal
              service: maas_db
        import_resources:
          jobs:
            - maas-bootstrap-admin-user
          services:
            - endpoint: internal
              service: maas_region
            - endpoint: internal
              service: maas_db
        rack_controller:
          jobs:
            - maas-export-api-key
          services:
            - endpoint: internal
              service: maas_region
        region_controller:
          jobs:
            - maas-db-sync
          services:
            - endpoint: internal
              service: maas_db
    manifests:
      configmap_ingress: false
      ingress_region: false
      maas_ingress: false
      rack_statefulset: true
      region_statefulset: true
      test_maas_api: false
