# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: maas
spec:
  chart:
    spec:
      version: 0.1.5
  dependsOn:
    - name: default-cluster-issuer
      namespace: cert-manager
    - name: postgresql-operator
      namespace: operators
  values:
    network:
      region_api:
        ingress:
          classes:
            namespace: cilium
            cluster: cilium
    storage:
      syslog:
        pvc:
          class_name: openebs-hostpath #ceph-block
      rackd:
        pvc:
          class_name: openebs-hostpath #ceph-block
    conf:
      # bind:
      #   override:
      #   append:
      #   cpus: 1
      # curtin:
      #   override: true
      #   late_commands:
      #     install_modules_extra: ["curtin", "in-target", "--", "apt-get", "-y", "install", "linux-modules-extra-4.15.0-88-generic"]
      cloudconfig:
        override: true
        sections:
          conf:
            cloudconfig:
              override: true
              sections:
                bootcmd:
                  - rm -fr /var/lib/apt/lists
                  - sysctl net.ipv6.conf.all.disable_ipv6=1
                  - sysctl net.ipv6.conf.default.disable_ipv6=1
                  - sysctl net.ipv6.conf.lo.disable_ipv6=0
      cache:
        enabled: true
      maas:
        # override:
        # append:
        url:
          maas_url: http://maas-region.ucp/MAAS
        # cgroups:
        #   disable_cgroups_region: true
        #   disable_cgroups_rack: true
        ntp:
          disable_ntpd_region: true
          disable_ntpd_rack: true
          use_external_only: true
          ntp_servers:
            - 0.ca.pool.ntp.org
            - 2.ca.pool.ntp.org
            - 3.ca.pool.ntp.org
            - 4.ca.pool.ntp.org
        dns:
          require_dnssec: no
          dns_servers:
            - 1.1.1.1
            - 9.9.9.9
        images:
          default_os: ubuntu
          default_image: focal
          default_kernel: ga-20.04
        credentials:
          secret:
            namespace: ucp
        syslog:
          remote_syslog: null
          log_level: DEBUG
        extra_settings:
          completed_intro: true
          enable_analytics: false
          network_discovery: disabled
          active_discovery_interval: 0
          enlist_commissioning: false
        system_user: null
        system_passwd: null
    pod:
      replicas:
        rack: 1
        region:
        syslog: 1
      resources:
        enabled: false
    endpoints:
      maas_ingress:
        hosts:
          error_pages: null
          monitor: null
      maas_syslog:
        host_fqdn_override:
          public: maas.ucp.svc.cluster.local
      maas_region:
        name: maas-region
        scheme:
          default: http
        host_fqdn_override:
          public: maas.ucp.svc.cluster.local
    dependencies:
      static:
        rack_controller:
          services:
            - service: maas_region
              endpoint: internal
          jobs:
            - maas-export-api-key
        region_controller:
          jobs:
            - maas-db-sync
          services:
            - service: maas_db
              endpoint: internal
        db_init:
          services:
            - service: maas_db
              endpoint: internal
        db_sync:
          jobs:
            - maas-db-init
        bootstrap_admin_user:
          jobs:
            - maas-db-sync
          services:
            - service: maas_region
              endpoint: internal
            - service: maas_db
              endpoint: internal
        import_resources:
          jobs:
            - maas-bootstrap-admin-user
          services:
            - service: maas_region
              endpoint: internal
            - service: maas_db
              endpoint: internal
        export_api_key:
          jobs:
            - maas-bootstrap-admin-user
          services:
            - service: maas_region
              endpoint: internal
            - service: maas_db
              endpoint: internal
    manifests:
      configmap_ingress: false
      ingress_region: false
      maas_ingress: false
      rack_statefulset: true
      region_statefulset: true
      test_maas_api: false
    cert_manager:
      enabled: false
      create: false
      issuer:
        kind: Issuer
        name: default-ca-issuer
