# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  dependsOn:
    - name: cilium-ca-issuer
    - name: prometheus
      namespace: observability
  values:
    k8sServiceHost: 192.168.1.64
    bandwidthManager:
      bbr: false
    l2announcements:
      enabled: true
      leaseDuration: 3s
      leaseRenewDeadline: 1s
      leaseRetryPeriod: 500ms
    ingressController:
      loadbalancerMode: shared
    hubble:
      tls:
        auto:
          certManagerIssuerRef:
            group: cert-manager.io
            kind: Issuer
            name: cilium-ca-issuer
          method: certmanager
      ui:
        enabled: true
    ipv4NativeRoutingCIDR: 192.168.1.0/24
    devices:
      - eth0
    operator:
      replicas: 1
