{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cosign-gatekeeper-provider.fullname" . }}-public-key
  labels:
    {{- include "cosign-gatekeeper-provider.labels" . | nindent 4 }}
spec:
  type: Opaque
  data:
    publicKey: {{ .Values.secrets.publicKey | b64encode }}
{{- end }}
