# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: capi-byoh
spec:
  controlPlane:
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: ByoMachineTemplate
        name: byoh-control-plane
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: K0smotronControlPlane
      name: byoh-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: ByoClusterTemplate
      name: byoh
  patches:
    - definitions:
        - jsonPatches:
            - op: add
              path: /spec/template/spec/controlPlaneEndpoint
              valueFrom:
                template: |
                  host: {{ .controlPlaneEndpointAddr }}
                  port: 6443
          selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: ByoClusterTemplate
            matchResources:
              infrastructureCluster: true
      description: Sets the control plane endpoint.
      name: controlPlaneEndpointAddr
    - definitions:
        - jsonPatches:
            - op: add
              path: /spec/k0sVersion
              valueFrom:
                variable: k0sVersion
          selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: K0smotronControlPlane
            matchResources:
              controlPlane: true
        - jsonPatches:
            - op: add
              path: /spec/k0sVersion
              valueFrom:
                variable: k0sVersion
          selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: K0sWorkerConfig
            matchResources:
              machineDeploymentClass:
                names:
                  - default-worker
      description: Sets the k0s version.
      name: k0sVersion
    - definitions:
        - jsonPatches:
            - op: add
              path: /spec/persistence/type
              valueFrom:
                variable: persistenceType
          selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: K0smotronControlPlane
            matchResources:
              controlPlane: true
      description: Sets the persistence type.
      name: persistenceType
    - definitions:
        - jsonPatches:
            - op: add
              path: /spec/service/type
              valueFrom:
                variable: serviceType
          selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: K0smotronControlPlane
            matchResources:
              controlPlane: true
      description: Sets the service type.
      name: serviceType
    - definitions:
        - jsonPatches:
            - op: add
              path: /spec/template/spec/bundleLookupBaseRegistry
              valueFrom:
                variable: bundleLookupBaseRegistry
          selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: ByoClusterTemplate
            matchResources:
              infrastructureCluster: true
      description: Sets the bundle lookup base registry.
      name: bundleLookupBaseRegistry
  variables:
    - name: controlPlaneEndpointAddr
      required: true
      schema:
        openAPIV3Schema:
          default: ""
          description: The address of the control plane endpoint.
          type: string
    - name: k0sVersion
      required: false
      schema:
        openAPIV3Schema:
          default: v1.27.2-k0s.0
          description: The k0s version to use. This must be a valid k0s version.
          type: string
    - name: persistenceType
      required: false
      schema:
        openAPIV3Schema:
          default: emptyDir
          description: The persistence type to use.
            One of emptyDir, hostPath, localVolume.
          type: string
    - name: serviceType
      required: false
      schema:
        openAPIV3Schema:
          default: NodePort
          description: The service type to use.
            One of ClusterIP, NodePort, LoadBalancer.
          type: string
    - name: bundleLookupBaseRegistry
      required: false
      schema:
        openAPIV3Schema:
          default: https://projects.registry.vmware.com/cluster_api_provider_bringyourownhost
          description: The base registry to use for bundle lookup.
          type: string
  workers:
    machineDeployments:
      - class: default-worker
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: K0sWorkerConfig
              name: byoh-worker-bootstraptemplate
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: ByoMachineTemplate
              name: byoh-worker-machinetemplate
