apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: cicd
spec:
  chart:
    spec:
      chart: bitnamicharts/harbor
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: docker
        namespace: sre
      version: 16.7.3
  install:
    crds: Create
    createNamespace: true
    replace: true
  interval: 1m0s
  postRenderers:
  - kustomize:
      images:
      - name: docker.io/bitnami/harbor-adapter-trivy
      - name: docker.io/bitnami/harbor-core
      - name: docker.io/bitnami/harbor-exporter
      - name: docker.io/bitnami/harbor-jobservice
      - name: docker.io/bitnami/harbor-notary-server
      - name: docker.io/bitnami/harbor-notary-signer
      - name: docker.io/bitnami/harbor-portal
      - name: docker.io/bitnami/harbor-registry
      - name: docker.io/bitnami/harbor-registryctl
      - name: docker.io/bitnami/nginx
      - name: docker.io/bitnami/os-shell
      - name: docker.io/bitnami/postgresql
  upgrade:
    crds: CreateReplace
  values: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kasten
  namespace: ucp
spec:
  chart:
    spec:
      chart: k10
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kasten
      version: 6.0.3
  dependsOn:
  - name: prometheus
    namespace: observability
  install:
    crds: Create
    createNamespace: true
    replace: true
  interval: 1m0s
  postRenderers:
  - kustomize:
      images:
      - name: gcr.io/kasten-images
      - name: ghcr.io/dexidp/dex
      - name: ghcr.io/kanisterio/kanister-tools
  upgrade:
    crds: CreateReplace
  values:
    auth:
      groupAllowList: []
      k10AdminGroups: []
      k10AdminUsers: []
      oidcAuth:
        enabled: true
        secretName: k10-oidc-auth
    encryption:
      primaryKey:
        vaultTransitKeyName: kasten
        vaultTransitPath: /transit
    eula:
      accept: true
    global:
      persistence:
        storageClass: ceph-rbd
      prometheus:
        external:
          baseURL: ""
          host: ""
          port: ""
    grafana:
      enabled: false
    metering:
      mode: airgap
    prometheus:
      networkPolicy:
        enabled: false
      server:
        enabled: false
    vault:
      secretName: k10-vault-auth
