# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: capi-capd
spec:
  controlPlane:
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: capd-control-plane
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: K0smotronControlPlane
      name: capd-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DockerClusterTemplate
      name: capd
  patches:
    - definitions:
        - jsonPatches:
            - op: add
              path: /spec/k0sVersion
              valueFrom:
                variable: k0sVersion
          selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: K0smotronControlPlane
            matchResources:
              controlPlane: true
        - jsonPatches:
            - op: add
              path: /spec/k0sVersion
              valueFrom:
                variable: k0sVersion
          selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: K0sWorkerConfig
            matchResources:
              machineDeploymentClass:
                names:
                  - default-worker
      description: Sets the k0s version.
      name: k0sVersion
    - definitions:
        - jsonPatches:
            - op: add
              path: /spec/persistence/type
              valueFrom:
                variable: persistenceType
          selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: K0smotronControlPlane
            matchResources:
              controlPlane: true
      description: Sets the persistence type.
      name: persistenceType
    - definitions:
        - jsonPatches:
            - op: add
              path: /spec/service/type
              valueFrom:
                variable: serviceType
          selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: K0smotronControlPlane
            matchResources:
              controlPlane: true
      description: Sets the service type.
      name: serviceType
    - definitions:
        - jsonPatches:
            - op: add
              path: /spec/template/spec/customImage
              valueFrom:
                template: |
                  kindest/node:{{ .builtin.machineDeployment.version | replace "+" "_" }}
          selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: DockerMachineTemplate
            matchResources:
              machineDeploymentClass:
                names:
                  - default-worker
        - jsonPatches:
            - op: add
              path: /spec/template/spec/customImage
              valueFrom:
                template: |
                  kindest/node:{{ .builtin.controlPlane.version | replace "+" "_" }}
          selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: DockerMachineTemplate
            matchResources:
              controlPlane: true
      description:
        Sets the container image that is used for running dockerMachines
        for the controlPlane and default-worker machineDeployments.
      name: customImage
    - definitions:
        - jsonPatches:
            - op: add
              path: /spec/template/spec/customImage
              value: kindest/node:v1.23.17@sha256:f77f8cf0b30430ca4128cc7cfafece0c274a118cd0cdb251049664ace0dee4ff
          selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: DockerMachineTemplate
            matchResources:
              machineDeploymentClass:
                names:
                  - default-worker
      description:
        Sets the container image for MD DockerMachineTemplates using Kubernetes
        v1.23.17.
      enabledIf: '{{ semverCompare "v1.23.17" .builtin.machineDeployment.version }}'
      name: replaceImage-v1.23.17-machineDeployment
    - definitions:
        - jsonPatches:
            - op: add
              path: /spec/template/spec/customImage
              value: kindest/node:v1.23.17@sha256:f77f8cf0b30430ca4128cc7cfafece0c274a118cd0cdb251049664ace0dee4ff
          selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: DockerMachineTemplate
            matchResources:
              controlPlane: true
      description:
        Sets the container image for CP DockerMachineTemplates using Kubernetes
        v1.23.17.
      enabledIf: '{{ semverCompare "v1.23.17" .builtin.controlPlane.version }}'
      name: replaceImage-v1.23.17-controlPlane
  variables:
    - name: k0sVersion
      required: false
      schema:
        openAPIV3Schema:
          default: v1.27.2-k0s.0
          description: The k0s version to use. This must be a valid k0s version.
          type: string
    - name: persistenceType
      required: false
      schema:
        openAPIV3Schema:
          default: emptyDir
          description: The persistence type to use.
            One of emptyDir, hostPath, localVolume.
          type: string
    - name: serviceType
      required: false
      schema:
        openAPIV3Schema:
          default: NodePort
          description: The service type to use.
            One of ClusterIP, NodePort, LoadBalancer.
          type: string
  workers:
    machineDeployments:
      - class: default-worker
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: K0sWorkerConfig
              name: capd-worker-bootstraptemplate
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: DockerMachineTemplate
              name: capd-worker-machinetemplate
