---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 6443
  disableDefaultCNI: false
  ipFamily: ipv4
  kubeProxyMode: ipvs
featureGates:
  UserNamespacesSupport: true
nodes:
  - role: control-plane
    labels: {}
    extraMounts: []
    #  - hostPath: /var/run/docker.sock
    #    containerPath: /var/run/docker.sock
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        listenAddress: 0.0.0.0
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        listenAddress: 0.0.0.0
        protocol: TCP
