---
apiVersion: cloudos.anselm.es/v1alpha1
kind: MachineDefinition
metadata:
  name: network
  namespace: infra
spec:
  evpn:
    loopback: 10.1.0.64
    management: 10.0.0.64/24
    anycast:
      address:
        ip: 192.168.11.1
        mac: 00:00:00:00:00:00
    l2:
      configRef:
        name: net
    evpn:
      configRef:
        name: net
