---
version: "3.9"
services:
  k0s:
    cgroup: host
    command: k0s controller --enable-worker --no-taints
    container_name: k0s
    hostname: k0s
    image: docker.io/k0sproject/k0s:v1.28.4-k0s.0
    network_mode: bridge
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - 80:80
      - 443:443
      - 6443:6443
      - 8080:80
      - 8443:443
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/run
    volumes:
      - ./cluster.yaml:/etc/k0s/k0s.yaml:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/k0s
