# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-userconfig
  namespace: iam
data:
  oidc-auth.hcl: |
    path "identity/oidc/provider/vault/authorize" {
      capabilities = [ "read" ]
    }
  oidc-admin.hcl: |
    # To create an entity and entity alias. Enable and configure Vault as an OIDC provider
    path "identity/*" {
      capabilities = [ "create", "read", "update", "delete", "list" ]
    }

    # To enable userpass auth method
    path "sys/auth/userpass" {
      capabilities = [ "create", "read", "update", "delete" ]
    }

    # To create a new user, "end-user" for userpass
    path "auth/userpass/users/*" {
      capabilities = [ "create", "read", "update", "delete", "list" ]
    }
  admins.hcl: |
    # Allow managing leases
    path "sys/leases/*"
    {
      capabilities = ["create", "read", "update", "delete", "list", "sudo"]
    }

    # Manage auth methods broadly across Vault
    path "auth/*"
    {
      capabilities = ["create", "read", "update", "delete", "list", "sudo"]
    }

    # Create, update, and delete auth methods
    path "sys/auth/*"
    {
      capabilities = ["create", "update", "delete", "sudo"]
    }

    # List auth methods
    path "sys/auth"
    {
      capabilities = ["read"]
    }

    # List existing policies
    path "sys/policies/acl"
    {
      capabilities = ["read","list"]
    }

    # Create and manage ACL policies
    path "sys/policies/acl/*"
    {
      capabilities = ["create", "read", "update", "delete", "list", "sudo"]
    }

    # List, create, update, and delete key/value secrets
    path "secret/*"
    {
      capabilities = ["create", "read", "update", "delete", "list", "sudo"]
    }

    # Manage secret engines
    path "sys/mounts/*"
    {
      capabilities = ["create", "read", "update", "delete", "list", "sudo"]
    }

    # List existing secret engines.
    path "sys/mounts"
    {
      capabilities = ["read"]
    }

    # Read health checks
    path "sys/health"
    {
      capabilities = ["read", "sudo"]
    }
