# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
spec:
  dependsOn:
    - name: prometheus
      namespace: observability
  values:
    global:
      storageClass: ceph-block
    server:
      resources:
        limits: {}
        requests: {}
      extraVolumes:
        - name: vault-script
          configMap:
            name: vault-script
            defaultMode: 0755
      extraVolumeMounts:
        - mountPath: /vault/userconfig/scripts
          name: vault-script
          readOnly: true
      sidecars:
        - name: vault-script
          image: docker.io/bitnami/vault:1.8.1-debian-10-r0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - >-
              sleep 5 && cp /vault/userconfig/scripts/vault-unseal.sh
              /tmp/vault-unseal.sh && chmod +x /tmp/vault-unseal.sh &&
              /tmp/vault-unseal.sh
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: observability
    csiProvider:
      enabled: false
      provider:
        resources:
          limits: {}
          requests: {}
      agent:
        resources:
          limits: {}
          requests: {}
    injector:
      resources:
        limits: {}
        requests: {}
