# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  dependsOn:
    - name: ceph-ca-issuer
    - name: prometheus
      namespace: observability
    - name: rook-ceph-operator
  # postRenderers:
  #   - kustomize:
  #       images:
  #         - name: quay.io/ceph/ceph
  #           newName: ghcr.io/gpu-ninja/ceph-images/ceph
  #           newTag: latest
  values:
    cephBlockPools: []
    cephClusterSpec:
      crashCollector:
        disable: true
      external:
        enable: true
      healthCheck:
        daemonHealth:
          mon:
            disabled: false
            interval: 45s
      skipUpgradeChecks: true
    cephFileSystems: []
    cephObjectStores: []
