# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  dependsOn:
    - name: prometheus
      namespace: observability
  values:
    resources:
      limits: {}
      requests: {}
    csi:
      provisionerReplicas: 1
      csiCephFSPluginResource: |
        - name : driver-registrar
          resources:
            requests: {}
            limits: {}
        - name : csi-cephfsplugin
          resources:
            requests: {}
            limits: {}
        - name : liveness-prometheus
          resources:
            requests: {}
            limits: {}
      csiCephFSProvisionerResource: |
        - name : csi-provisioner
          resources:
            requests: {}
            limits: {}
        - name : csi-resizer
          resources:
            requests: {}
            limits: {}
        - name : csi-attacher
          resources:
            requests: {}
            limits: {}
        - name : csi-snapshotter
          resources:
            requests: {}
            limits: {}
        - name : csi-cephfsplugin
          resources:
            requests: {}
            limits: {}
        - name : liveness-prometheus
          resources:
            requests: {}
            limits: {}
      csiNFSPluginResource: |
        - name : driver-registrar
          resources:
            requests: {}
            limits: {}
        - name : csi-nfsplugin
          resources:
            requests: {}
            limits: {}
      csiNFSProvisionerResource: |
        - name : csi-provisioner
          resources:
            requests: {}
            limits: {}
        - name : csi-nfsplugin
          resources:
            requests: {}
            limits: {}
        - name : csi-attacher
          resources:
            requests: {}
            limits: {}
      csiRBDPluginResource: |
        - name : driver-registrar
          resources:
            requests: {}
            limits: {}
        - name : csi-rbdplugin
          resources:
            requests: {}
            limits: {}
        - name : liveness-prometheus
          resources:
            requests: {}
            limits: {}
      csiRBDProvisionerResource: |
        - name : csi-provisioner
          resources:
            requests: {}
            limits: {}
        - name : csi-resizer
          resources:
            requests: {}
            limits: {}
        - name : csi-attacher
          resources:
            requests: {}
            limits: {}
        - name : csi-snapshotter
          resources:
            requests: {}
            limits: {}
        - name : csi-rbdplugin
          resources:
            requests: {}
            limits: {}
        - name : csi-omap-generator
          resources:
            requests: {}
            limits: {}
        - name : liveness-prometheus
          resources:
            requests: {}
            limits: {}
    discover:
      resources: {}
