# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  dependsOn:
    - name: default-cluster-issuer
      namespace: cert-manager
    - name: prometheus
      namespace: observability
  values:
    # routingMode: native
    tunnel: disabled
    ipv4NativeRoutingCIDR: 192.168.11.0/24
    devices:
      - oam
    l2announcements:
      enabled: true
    # securityContext:
    #   privileged: true
    ingressController:
      enabled: true
      secretsNamespace:
        create: false
        name: kube-system
    externalIPs:
      enabled: true
    hostFirewall:
      enabled: true
    monitor:
      enabled: true
    loadBalancer:
      mode: dsr
      serviceTopology: true
      algorithm: maglev
      l7:
        backend: envoy
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    dashboards:
      enabled: true
      namespace: observability
    proxy:
      prometheus:
        enabled: true
    gatewayAPI:
      enabled: true
      secretsNamespace:
        create: false
        name: kube-system
    operator:
      replicas: 1
      dashboards:
        enabled: true
        namespace: observability
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
