#!/bin/sh

# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

set -eux

# install microk8s
snap install microk8s --channel=1.27/beta --classic

# TODO: generate config
# tee microk8s-config.yaml <<EOF
# EOF
# TODO: apply config
# snap set microk8s config="$(cat microk8s-config.yaml)"

# add self-signed issuer
cat <<-EOF | microk8s kubectl apply -f -
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed
spec:
  selfSigned: {}
EOF

# FIXME: to configure grafana
cat <<EOF | microk8s kubectl apply -f -
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: observability
  annotations:
    kubernetes.io/acme-tls: "true"
    cert-manager.io/cluster-issuer: self-signed
spec:
  ingressClassName: public
  defaultBackend:
    service:
      name: kube-prom-stack-grafana
      port:
        number: 80
  tls:
    - secretName: grafana-tls
      hosts:
        - "grafana.${DOMAIN}"
  rules:
    - host: "grafana.${DOMAIN}"
EOF
