# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
apiVersion: v1
kind: Secret
metadata:
  name: default-ca-key-pair
  namespace: cert-manager
type: Opaque
data:
  tls.crt: ENC[AES256_GCM,data:LAG5K/7i+Vq3Y3E6K4Fk1Oo6D/cNS5RG9GO1/EV3ybodrRspMl6KGg8OG37TbYL8DTLQ+zxiExWf7cVysSd0zVylV0aYr4QSz+1P+x5GhiHCKLvwi+TElps30Trg9gPgkPOk6LEm6GjrdaDhalY6ldVFnq3KnKb1+IjKdrVQCUDVhPYg2Msu6qV3EELqxvqU88/bQriNa9SMBYbjs301E7McG7wt3nFqoVnPSHOhgxS346K1tUh6urnBu9xv6bzZIDrEW9DvszxwE/sY932r01wcD6LLw4pikJIBsnOKWV9AkTgHjAzwZJ71Vb3Qt0bOTZZAS0/q3vTkXQQDXvk7ANTXzHVZ+VdpPSPkMNIiZ7ExQ/lp89thKAONKUHZx8b2h4jZsb6KEDrevH2Zm910Idz7AYt6kby72UrOzIeyu81Oj6IRZ+/wAx3cQJ3pdk3dUPJwPB0mnoippAJ+2DWgy42al9B6Di2RXRgThTWPxSMztah5GirOL+zJWVk9Z+VRctD13JoOoM1nRd6mqbj34FxaxsdBkaMwRtOul+VhyYgxa+1KXHaul6m4ogkNANlHniqLZEFphTipH9Vt/8ISgkWwqxpuhY+XlBECZA3mbs/Avd2jsqzY1p83w2n8OAkVX9kiBNln30eHNwqzEwmjXqXhK0E6/WVx8w3J1V0mh3ZEBuvdyYnX+Fyp9oGnuMHgUhfyeGN44J5EwwA2zbp4rqgLhZwYaeeifohvInmiruR7pyX3vj4aftRtff234e0TjduK912CDVbKETu5oQtPPrDN0ynJEEq8AjFQy+cNVhnRnp0wT6D8tmbosl9sEhaX4hFZhytVsS6GUc1Ea4+hgm3PUxSXGjrjZLlkPN2+w4aUU+LmipZfNvAPNLgDc4trh0FqkM8A7rDQe4EcrhC/3sYmOV2rajHujzCjopNi3yyaAqvjiVLGxgMbFjdv8VSasQXMMoeafthJxWVBZiRIIf+4br3TyUIZ7izg4SBjvkVH5WCu/VLpbRlj8yI64zFTNmoECqwDlvjsokqsobxDKw2PEEZH8hfbjKJjVD7Lbsh90S3z+7OSmFZIGbHBblNJoY2+bPJxCPWCYzd1a1HcVWSPmQ45fiJL5JvZpcVK/NEoW+W4tib6ay23aHbp3q4UCpdhuqPcncrzWdugcmvOBy8uT0QBO/jMuTgHFcUAnCW9sv1BsUWMtDtvJobsUmONDn98adslCuWHHWlagt17LhbHZYSV4ANx5mYS1NOMft1qqiv9KW6SXOO/PLPskm1N2wT/XzxvZFLx572mL4utZjxaxGkdH9WU9XTwip+2XarxPwlaJp7RAIAaub8JQEC+1KGKEgi4qwoKR307zppTt8nwnaQDF7n+rG2XRBXDBFPWG+GwOfo1n8+M1zYUVWVDR4rYd2RREPQu7GbVzpXt7fo5svp470e81wxlaktAih3CrKW/cvTHTOCO5+MOn6qJ/Adx8TNk7tm31sH8RQTzf28fhfMOrn1aoPsXnzA5llbJ79wbVDI5N04EgdLm9ZBXnLknRu4VUuHIylZM8Zv1X1X4z/xjbSZS4A91aTMA1qo2KFGWv3BzPVq1xGjjAK1mTeDz9rY4UXUUwfvMu+gi4PC0kHXRtaemxFSGGNb6q6gj3JxhDREtEzr/qZvZAyy7N3UVXErBN4NEBa60wamYFBxBU2nD+kBm1KIrDywXvK00//ogm5bfhJGtD5SD5eP1sJD8aZk5vh0haeXLia7uA6OY2TQa0NGDM0Ps6LxNgC0jCH1KN9jNCGCLlrKCpNrmva+PJIl1HO1FdqPNdq2ZmKLqAlAoOWfZjulzWmTt6lv6BC/ZwWQ5UNW9rnkXJgFo854nyH2p2Bg4nbsEEmLAtucbh5z6qySIqulPL8jcQYnnulRppA4SaVu4j4UCHub4LS6PzV7klfdxMwxnya7rlAPCS5djr0nUkiO40/7Pt/ue8hy/lMbUxlOQ4m3jhRypJ84y5DOs9AY/7BT6Lt0RFBQBrqE/AY4CWtRzLmdnpd7k+rrsVh/oG81Vu+FgeSg3V7uxcT+FfTwv4n77dA6QB+W4xod/J4fuOs455KBNLmVlNojbKnxY/Q==,iv:OMO8qCH81OJh1Et+nLVD0yKoZ/4GUWiecH6kO6ABB+o=,tag:jhnHUwVegvpQdsDosFDidQ==,type:str]
  tls.key: ENC[AES256_GCM,data:3QAhH6DtC//YOtwjtibYN9MwJjZQ/1cq+dMPmdKs06P4GWGG81CDlmK+7xgR7nVAwgfIVD7enviZKeed4CEBDLx27ZtCqp83jd3dYomnbqMhpw5TMH4xYcPVTomsCaGDfsXg9C/m6WlUYJQY3aXVdpx/eZ06ZDr65SwakIFG0CfOATDjqIpUnT4pgx1HlSTGH6KcJbH8SarSzYR7MhwR/hUIAdxiefzZpqdctiCDjuFAkMNHAtS4fk7IKvCYC5fvRAmxqJrk2FpRLi8N0WWMOzm19sXlIYXepD06Nl1usceUFJrHd98dhZtSvs1YJXuyxcyeLzLDVOU4/XxGM2jSH9ZIXgTxYbmBWlAxaJgdjX47JHLAOvDBlgA+53FdD/DkotcvrwCZ/YahYedc54k5ivX3yvA+fjEWNcpOdwDotKLzhfhnplM1yhPt2FQSEprp5hF4SDzV8ppWejFV,iv:gPvjJem6rn7pgStO31akUxzxCyCmhwksrP3YRrqydbU=,tag:a+UWypNtdBcFnLMjXbmHYQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-07-08T17:17:26Z"
  mac: ENC[AES256_GCM,data:Qq1d5edgJWNVhdpxq0NiVxKiTMEBDWvi9B+Jo+aTRzGL/RZgrSUqLmY/uP5CCh5xbrkae9pbTe6EebQgxrzmvSOl4X5Ld4FMb6XEZkOetTRyk+4280MKeiBOK8b5NN7enrstfGZxOyaTKPsBU2Wn9AMdbe+4kkCK/DAF+kEGEOk=,iv:LetGsTKSf8INcgXp7XH6YgjSVYiy2F1Q1ilLCqeMtT8=,tag:M7568Xg901lI7D+KVEnxzA==,type:str]
  pgp:
    - created_at: "2023-07-08T17:17:25Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMAwXO/OIgjsG2AQ//QYwIiwGHqGG0WwgFiLATgpsdKnIfPrOOelpon+O+FJFN
        NEMme9TJwGeT3gjuG0cjr+4/bAKBc7x6vqggbsO7oVhyo0VQYWkAOJiejOyroNSj
        fhYNhCjo9DNTvwsCreiXQA4vW4exCp5clLPwxlMNZXKqSZWaMKA9KyEmc+zOXmg3
        bw8td7wRFOJKfs13C9JP/tnLVyf3s1iA+KuKggHgUq6+sa2VHUFFNVvXcUMqQCkp
        hEZVYfQH5ovFjtWqjKB/+Rh4f9f02NTxVBIFlhgr1UpMx0C3R26WaGwBNMO/qSAg
        ftiUv4YUjYlX4uG3lCTV4orJe8PjLxg5kOfB8vlEfGxFiWTPKgHugR0GH68U7VyK
        KLwCrm5SKeghB/dG4zrERajaFFmUf/rGsUKoZOJhWx4HmuTEBhyZQtshPNq4vFad
        q6mTlXf9iuCQziJpckiuqHezEi6M0ToqpdJn9+jzLFDEwR4udJznBmT9dmHWWWb6
        5W9nWxmms6s5wkZILWKQ5/5nJUcnhycHZRyx+Xh/zmrDLuTOxUei3Cjnoo9OOuJ0
        OZVv6R5X7AlvT+mjdX/UX5G1cAiOzq1CRrzKIEtTAn9IHt0DD63ggmzkvbw8dvWC
        gRYR3eoCg3U+X8iDcj++akSBZ1jSkuAaCb/YnvEI57O4sc7egtvf4xedS0hHWBLU
        ZgEJAhATJKFfMCZJgOP2pa7d7njYP241TWudcHU14WcalOd3iUQNXLYyY94NvDl6
        rladdwc+UU1zxGLLvr+mgrGtjanFMCINRrr83LgqTn5T5tPmFYo/hegxF3nzXnE9
        xqTJPTS5dw==
        =09aO
        -----END PGP MESSAGE-----
      fp: 11AE5ED9ED4248C1318397B9AB442CFDB8ED91E4
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
