# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox
spec:
  dependsOn:
    - name: postgresql
    - name: prometheus
      namespace: observability
    - name: redis
  values:
    global:
      labels: {}
    netbox:
      auth_password_validators:
        - name: django.contrib.auth.password_validation.MinimumLengthValidator
          options:
            - key: min_length
              value: 8
      cors_origin_allow_all: false
      date_time:
        date_format: N j, Y
        short_date_format: Y-m-d
        time_format: g:i a
        short_time_format: H:i:s
        date_time_format: N j, Y g:i a
        short_date_time_format: Y-m-d H:i
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
