# Copyright (c) 2023 Schubert Anselme <schubert@anselm.es>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: litmus
spec:
  chart:
    spec:
      chart: litmus
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: litmuschaos
      version: 2.15.10
  install:
    crds: CreateReplace
    createNamespace: true
    replace: true
  interval: 1m0s
  upgrade:
    crds: CreateReplace
  postRenderers:
    - kustomize:
        images:
          - name: docker.io/curl
          - name: docker.io/litmuschaos/argoexec
          - name: docker.io/litmuschaos/chaos-exporter
          - name: docker.io/litmuschaos/chaos-operator
          - name: docker.io/litmuschaos/chaos-runner
          - name: docker.io/litmuschaos/litmusportal-auth-server
          - name: docker.io/litmuschaos/litmusportal-event-tracker
          - name: docker.io/litmuschaos/litmusportal-frontend
          - name: docker.io/litmuschaos/litmusportal-server
          - name: docker.io/litmuschaos/litmusportal-subscriber
          - name: docker.io/litmuschaos/upgrade-agent-cp
          - name: docker.io/litmuschaos/workflow-controller
