# TODO: move to labsonline/cicd
# and add to gates (cicd / build / image)
name: Build

on:
  - push

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1  https://github.com/actions/checkout/commit/b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0 https://github.com/docker/setup-qemu-action/commit/68827325e0b33c7199eb31dd4e31fbe9023e06e3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0 https://github.com/docker/setup-buildx-action/commit/f95db51fddba0c2d1ec667646a06c2ce06100226
      # TODO: login when mergin to main
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0 https://github.com/docker/login-action/commit/343f7c4344506bcbf9b4de18042ae17996df046d
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.BUILD_TOKEN }}
      - name: Build
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.0.0 https://github.com/docker/build-push-action/commit/0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: false # TODO: push when mergin to main
          file: ./build/pkg/img/Dockerfile
          cache-from: type=registry,ref=ghcr.io/sanselme/labs:latest
          tags: |
            sanselme/labs:${{ github.sha }},
            sanselme/labs:v0.1.0,
            sanselme/labs:latest
          labels: |
            org.opencontainers.image.authors=Schubert Anselme <schubert@anselm.es>,
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }},
            org.opencontainers.image.description=Inception,
            org.opencontainers.image.documentation=https://github.com/sanselme/labs/blob/main/README.md,
            org.opencontainers.image.licenses=GPL-3.0-or-later,
            org.opencontainers.image.revision=${{ github.sha }},
            org.opencontainers.image.source=https://github.com/sanselme/labs,
            org.opencontainers.image.title=Inception,
            org.opencontainers.image.url=https://github.com/users/sanselme/packages/container/package/labs%2Finception
            org.opencontainers.image.version=${{ github.sha }},
      # TODO: sign image when merging to main
