# TODO: move to labsonline/cicd
# and add to review (cicd / review / scan)
name: Scan

on:
  - push
  - pull_request

permissions: read-all

jobs:
  scanning:
    name: GitGuardian scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1  https://github.com/actions/checkout/commit/b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: GitGuardian scan
        uses: GitGuardian/ggshield-action@4848e499be8c740d2d71526182c1343d577d7322 # v1.20.0 https://github.com/GitGuardian/ggshield-action/commit/4848e499be8c740d2d71526182c1343d577d7322
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
