name: Review

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions: read-all

jobs:
  review:
    uses: labsonline/cicd/.github/workflows/review.yml@6e038f38f0819ffec0ea23e23efd8a1a0a4a4537 # v0.1.4 https://github.com/labsonline/cicd/commit/6e038f38f0819ffec0ea23e23efd8a1a0a4a4537
    permissions:
      pull-requests: write
